apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: agw-ingress
  namespace: agw-production
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "1m"
    nginx.ingress.kubernetes.io/limit-rps: "20"
    nginx.ingress.kubernetes.io/limit-connections: "10"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "10"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "30"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Frame-Options: DENY";
      more_set_headers "X-Content-Type-Options: nosniff";
      more_set_headers "Referrer-Policy: strict-origin-when-cross-origin";
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - artisangemworks.com
        - www.artisangemworks.com
      secretName: agw-tls
  rules:
    - host: artisangemworks.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: agw-app
                port:
                  number: 80
    - host: www.artisangemworks.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: agw-app
                port:
                  number: 80
